name: Publish to Gradle Plugin Portal

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Module to publish"
        type: choice
        required: true
        options:
          - all
          - idea-conventions
          - java-conventions
          - junit-conventions
          - kotlin-conventions
          - maven-publish-conventions
          - signing-conventions
          - sonarqube-conventions
          - spotless-conventions
          - versions-conventions

jobs:
  publish:
    runs-on: ubuntu-latest
    # Prevent two publish jobs from running at the same time.
    concurrency:
      group: publish
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Set up mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6
      - name: Publish all modules
        if: ${{ inputs.module == 'all' }}
        run: ./gradlew publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      - name: Publish single module — ${{ inputs.module }}
        if: ${{ inputs.module != 'all' }}
        run: ./gradlew :${{ inputs.module }}:publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
