name: Publish to Gradle Plugin Portal

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Module to publish"
        type: choice
        required: true
        options:
          - all
          - idea-conventions
          - java-conventions
          - junit-conventions
          - kotlin-conventions
          - maven-publish-conventions
          - signing-conventions
          - sonarqube-conventions
          - spotless-conventions
          - versions-conventions

jobs:
  publish:
    runs-on: ubuntu-latest
    # Prevent two publish jobs from running at the same time.
    concurrency:
      group: publish
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5
      - name: Publish all modules
        if: ${{ inputs.module == 'all' }}
        run: ./gradlew publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      - name: Publish single module — ${{ inputs.module }}
        if: ${{ inputs.module != 'all' }}
        run: ./gradlew :${{ inputs.module }}:publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
