name: Publish to Gradle Plugin Portal

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Module to publish"
        type: choice
        required: true
        options:
          - all
          - idea-conventions
          - java-conventions
          - junit-conventions
          - kotlin-conventions
          - maven-publish-conventions
          - signing-conventions
          - sonarqube-conventions
          - spotless-conventions
          - versions-conventions

jobs:
  publish:
    runs-on: ubuntu-latest
    # Prevent two publish jobs from running at the same time.
    concurrency:
      group: publish
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up mise
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6
      - name: Publish all modules
        if: ${{ inputs.module == 'all' }}
        run: ./gradlew publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      - name: Publish single module — ${{ inputs.module }}
        if: ${{ inputs.module != 'all' }}
        run: ./gradlew :${{ inputs.module }}:publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
